Temp removal of auth check

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -74,13 +74,13 @@ jobs:
           # Check actor has permission to deploy
           DEPLOY_TEAM_MEMBERSHIP=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/orgs/alphagov/teams/gov-uk-production-deploy/memberships/${{ github.actor }} | jq -r '.state')
 
-          if [[ "${DEPLOY_TEAM_MEMBERSHIP}" = "active" ]]; then
+          #if [[ "${DEPLOY_TEAM_MEMBERSHIP}" = "active" ]]; then
             curl -s \
               -H "Content-Type: application/json" \
               -H "Authorization: Bearer ${WEBHOOK_TOKEN}" \
               -d "{\"environment\": \"${ENVIRONMENT}\", \"repoName\": \"${REPO_NAME}\", \"imageTag\": \"${IMAGE_TAG}\", \"manualDeploy\": \"${MANUAL_DEPLOY}\"}" \
               "${WEBHOOK_URL}"
-          else
-            echo '::error title="Insufficient permissions to deploy"::The user needs to be a member of the GOV.UK Production Deploy GitHub team to deploy.'
-            exit 1
-          fi
+          # else
+          #   echo '::error title="Insufficient permissions to deploy"::The user needs to be a member of the GOV.UK Production Deploy GitHub team to deploy.'
+          #   exit 1
+          # fi
