Seperate step for permissions check to enable automatic deploys
This seperates the permissions check into another step in the set
automatic deploys workflows. This makes it consistent with the deploy
workflows and makes it easier to see when pemissions failed in the
GitHub UI.

diff --git a/.github/workflows/set-automatic-deploys-enabled.yaml b/.github/workflows/set-automatic-deploys-enabled.yaml
--- a/.github/workflows/set-automatic-deploys-enabled.yaml
+++ b/.github/workflows/set-automatic-deploys-enabled.yaml
@@ -71,25 +71,31 @@ jobs:
     name: Set automatic deploys
     runs-on: ubuntu-latest
     steps:
+      - name: Check deploy permissions
+        id: deploy-permissions
+        env:
+          GH_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
+          GITHUB_TEAM: gov-uk-production-deploy
+          GITHUB_USER: ${{ github.triggering_actor }}
+        run: |
+          TEAM_MEMBERSHIP=$(gh api orgs/alphagov/teams/${GITHUB_TEAM}/memberships/${GITHUB_USER} -q .state || echo "false")
+
+          if ! [[ "${TEAM_MEMBERSHIP}" = "active" || "${ENVIRONMENT}" = 'integration' ]]; then
+            echo "::error title=Insufficient permissions to deploy::User ${GITHUB_USER} needs to be a member of the ${GITHUB_TEAM} team"
+            exit 1
+          fi
+
       - name: Send webhook
+        if: steps.deploy-permissions.outcome == 'success'
         env:
           AUTOMATIC_DEPLOYS_ENABLED: ${{ inputs.automaticDeploysEnabled }}
           ENVIRONMENT: ${{ inputs.environment }}
           REPO_NAME: ${{ inputs.appName }}
           WEBHOOK_TOKEN: ${{ secrets.WEBHOOK_TOKEN }}
           WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
-          GITHUB_TOKEN: ${{ secrets.GOVUK_CI_GITHUB_API_TOKEN }}
         run: |
-          # Check actor has permission to deploy
-          DEPLOY_TEAM_MEMBERSHIP=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" https://api.github.com/orgs/alphagov/teams/gov-uk-production-deploy/memberships/${{ github.actor }} | jq -r '.state')
-
-          if [[ "${DEPLOY_TEAM_MEMBERSHIP}" = "active" ]]; then
-            curl -s \
-              -H "Content-Type: application/json" \
-              -H "Authorization: Bearer ${WEBHOOK_TOKEN}" \
-              -d "{\"environment\": \"${ENVIRONMENT}\", \"repoName\": \"${REPO_NAME}\", \"automaticDeploysEnabled\": \"${AUTOMATIC_DEPLOYS_ENABLED}\"}" \
-              "${WEBHOOK_URL}/set-automatic-deploys-enabled"
-          else
-            echo '::error title="Insufficient permissions to deploy"::The user needs to be a member of the GOV.UK Production Deploy GitHub team to deploy.'
-            exit 1
-          fi
+          curl -s \
+            -H "Content-Type: application/json" \
+            -H "Authorization: Bearer ${WEBHOOK_TOKEN}" \
+            -d "{\"environment\": \"${ENVIRONMENT}\", \"repoName\": \"${REPO_NAME}\", \"automaticDeploysEnabled\": \"${AUTOMATIC_DEPLOYS_ENABLED}\"}" \
+            "${WEBHOOK_URL}/set-automatic-deploys-enabled"
